(defun my-javascript-mode-hook ()
  (local-set-key [(return)] 'newline-and-indent)
  (setq indent-tabs-mode nil)
  (setq c-indent-level 4)
  (setq c-brace-imaginary-offset 0)
  (setq c-brace-offset -4)
  (setq c-argdecl-indent 4)
  (setq c-basic-offset 4)
  (setq c-label-offset -4)
  (setq js-indent-level 4)
  (setq tab-width 4)
  (flymake-mode))

(add-hook 'js-mode-hook 'my-javascript-mode-hook)

(defun my-java-mode-hook ()
  (local-set-key [(return)] 'newline-and-indent)
  (setq indent-tabs-mode nil)
  (setq c-indent-level 4)
  (setq c-brace-imaginary-offset 0)
  (setq c-brace-offset -4)
  (setq c-argdecl-indent 4)
  (setq c-basic-offset 4)
  (setq c-label-offset -4)
  (setq js-indent-level 4)
  (setq tab-width 4))

(add-hook 'java-mode-hook 'my-java-mode-hook)

