language: haskell
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
ghc:
  - 7.6
  - 7.8
before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  # PPA for Emacs nightlies
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install Emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox
  # Install and bootstrap cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
  # Install HLint to check our source.  We also install Alex and Happy, because
  # hlint needs recent versions of these
  - cabal install alex happy hlint
install:
  - cask install
script:
  - make EMACS=$EMACS compile
  - make HLINTFLAGS=-c lint
  - make EMACS=$EMACS test
